# Change these first
owner: BreadCity # Your GitHub organization or username, where this repository lives
repo: status.breadhub.cc # The name of this repository

sites:
  - name: Discord Redirect
    url: https://cord.breadhub.cc/
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.breadhub.cc
  # baseUrl: /your-repo-name
  logoUrl: https://breadcity.github.io/assets/0ed96455038595839fcd70e21dbcb066.webp
  name: BreadHub Uptime
  introTitle: "**BreadHub** is an advanced roblox Script-Hub."
  introMessage: "Made by people who care about the users, Bread Hub is a unique script-hub focused on a unique combination of reliability, performance, and an elegant UI like no other."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Discord
      href: https://cord.breadhub.cc/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
